# Server
server:
    port: 8080

# Spring
spring:
    application:
        name: pedido
    profiles:
        active: dev
    flyway:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: none
