spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
      show-sql: true
      database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
    properties:
      hibernate:
        format_sql: false
  flyway:
    locations: classpath:db/migration/postgres

pagamentos:
    service:
        url: http://a3d21b649f7bf4f05a5a4b6b714d225b-446223114.us-east-1.elb.amazonaws.com

producao:
    service:
        url: http://a4c445b217c104f46aaadc1eda4be52f-480546270.us-east-1.elb.amazonaws.com
